name: 'kirick13/build-npm-package-action'
description: 'Builds NPM package using my standard scripts.'
inputs:
  npm-token:
    description: 'NPM token.'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Extract tag for package from its version"
      run: |
        PACKAGE_VERSION="$(jq -r .version package.json)"
        if [[ $PACKAGE_VERSION == *.*.*-dev.* ]]; then
          echo "NPM_TAG=dev" >> $GITHUB_ENV
        elif [[ $PACKAGE_VERSION == *.*.*-beta.* ]]; then
          echo "NPM_TAG=beta" >> $GITHUB_ENV
        else
          echo "NPM_TAG=latest" >> $GITHUB_ENV
        fi
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.21
    - run: bun install
      shell: bash
    - run: bun run publish:npm --access public --provenance --tag ${{ env.NPM_TAG }}
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
    # - run: bun run redis:down || true
    #   shell: bash
  post: bun run redis:down || true
